googleAnalytics = 'G-8X3E23BYB7'
baseURL = 'https://serviceio.dev/'
languageCode = 'en-us'
title = 'Managing APIs with Service Infrastructure'

[params]
#BookLogo = 'yin.png'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'screenshots'
target = 'static/screenshots'
