googleAnalytics = 'G-99FDL1RV10'
baseURL = 'https://serviceinfra.dev/'
languageCode = 'en-us'
title = 'Managing APIs with Service Infrastructure'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'screenshots'
target = 'static/screenshots'
